function info = build_angle_lut_harness()
%BUILD_ANGLE_LUT_HARNESS Build the Stage-1 model without editing the source.
%
% The generated model is a save_system copy of
% FOC_fw_hifi_v1_0709backup.slx.  It adds a mechanical-domain encoder
% forward model, routes its selected electrical angle through the original
% controller latency block, and adds passive, phase-aligned logging taps.
%
% Numeric mode contracts:
%   sensor_mode       uint8(0) = LEGACY_ELECTRICAL
%                     uint8(1) = MECHANICAL_STAGE1 (saved default)
%   encoder_error_mode uint8(0) = off
%                      uint8(1) = fixed mechanical bias
%                      uint8(2) = periodic mechanical error (saved default)

thisFile = mfilename('fullpath');
modelsDir = fileparts(thisFile);
projectDir = fileparts(modelsDir);
repoRoot = fileparts(projectDir);

sourcePath = fullfile(repoRoot, 'FOC_fw_hifi_v1_0709backup.slx');
harnessPath = fullfile(modelsDir, 'angle_lut_harness.slx');
sourceModel = 'FOC_fw_hifi_v1_0709backup';
harnessModel = 'angle_lut_harness';

assert(isfile(sourcePath), 'Stage1:MissingSourceModel', ...
    'Source model not found: %s', sourcePath);

sourceHashBefore = local_sha256(sourcePath);

cacheRoot = fullfile(tempdir, 'codex_angle_lut_stage1');
if ~isfolder(cacheRoot)
    mkdir(cacheRoot);
end
Simulink.fileGenControl('set', ...
    'CacheFolder', cacheRoot, ...
    'CodeGenFolder', cacheRoot, ...
    'createDir', true);

if bdIsLoaded(harnessModel)
    close_system(harnessModel, 0);
end
if bdIsLoaded(sourceModel)
    close_system(sourceModel, 0);
end

load_system(sourcePath);
solverContract = local_solver_contract(sourceModel);
save_system(sourceModel, harnessPath);
close_system(sourceModel, 0);
load_system(harnessPath);

cleanupModel = onCleanup(@() local_close_without_saving(harnessModel));

assert(isequal(solverContract, local_solver_contract(harnessModel)), ...
    'Stage1:SolverContractChanged', ...
    'save_system copy did not preserve the solver contract.');

local_install_workspace_parameters(harnessModel);
local_parameterize_operating_point(harnessModel);
local_install_encoder_forward_model(harnessModel);
iabcMux = local_install_iabc_mux(harnessModel);
dutyNonideal = local_install_duty_nonideal(harnessModel, iabcMux);
plantVoltage = local_install_voltage_drop(harnessModel, iabcMux);
logNames = local_install_observer_taps( ...
    harnessModel, iabcMux, dutyNonideal, plantVoltage);

set_param(harnessModel, 'PreLoadFcn', '');
set_param(harnessModel, 'PostLoadFcn', '');
set_param(harnessModel, 'CloseFcn', '');

% Update once before saving so malformed ports or sample times fail here.
set_param(harnessModel, 'SimulationCommand', 'update');
assert(isequal(solverContract, local_solver_contract(harnessModel)), ...
    'Stage1:SolverContractChanged', ...
    'Harness edits changed the inherited solver contract.');

save_system(harnessModel, harnessPath);
close_system(harnessModel, 0);

sourceHashAfter = local_sha256(sourcePath);
assert(strcmpi(sourceHashBefore, sourceHashAfter), ...
    'Stage1:SourceModelModified', ...
    'The source model hash changed while building the harness.');

info = struct();
info.source_model = sourcePath;
info.harness_model = harnessPath;
info.source_sha256_before = sourceHashBefore;
info.source_sha256_after = sourceHashAfter;
info.source_unchanged = true;
info.sensor_mode_contract = struct( ...
    'LEGACY_ELECTRICAL', uint8(0), ...
    'MECHANICAL_STAGE1', uint8(1));
info.error_mode_contract = struct( ...
    'off', uint8(0), 'fixed', uint8(1), 'periodic', uint8(2));
info.logged_timeseries = logNames;
info.solver_contract = solverContract;

fprintf('Built %s\n', harnessPath);
fprintf('Source SHA256 unchanged: %s\n', sourceHashAfter);
fprintf('Logged timeseries: %s\n', strjoin(logNames, ', '));
end

function local_install_workspace_parameters(model)
mw = get_param(model, 'ModelWorkspace');

% Preserve the legacy parameter and make its zero value explicit.
mw.assignin('encoder_theta_offset_rad', 0);

mw.assignin('sensor_mode', uint8(1));
mw.assignin('encoder_error_mode', uint8(2));
mw.assignin('encoder_error_bias_m_rad', 0);
mw.assignin('encoder_error_amp1_m_rad', deg2rad(0.60));
mw.assignin('encoder_error_phase1_rad', 0);
mw.assignin('encoder_error_amp2_m_rad', deg2rad(0.30));
mw.assignin('encoder_error_phase2_rad', pi/4);
mw.assignin('theta0_e_rad', 0);

mw.assignin('angle_sample_period_s', 1 / mw.evalin('fpwm'));
mw.assignin('encoder_noise_std_m_rad', 0);
mw.assignin('encoder_noise_seed', uint32(20260818));
mw.assignin('stage1_current_noise_std_A', 0);
mw.assignin('stage1_current_noise_seed', uint32(20260818));
mw.assignin('stage1_ident_phase_s', mw.evalin('Ts'));
mw.assignin('T_ident', 1 / mw.evalin('fpwm'));
mw.assignin('stage1_overmod_epsilon', 1e-12);

% These variables existed in the source workspace but were not physically
% wired.  The harness connects them and saves zero defaults so legacy/off
% operation remains dynamically equivalent to the original model.
mw.assignin('pwm_min_pulse_duty', 0);
mw.assignin('pwm_deadtime_s', 0);
mw.assignin('inverter_voltage_drop_V', 0);

% The inherited block is labelled RPM, but its next gain is exactly 2*pi;
% its numerical input is therefore mechanical revolutions per second.
    mw.assignin('stage1_speed_target_rpm', 10/(2*pi));
    % Saved zero initial conditions preserve source-model startup when the
    % legacy-equivalence gate explicitly selects LEGACY_ELECTRICAL/off.
    % Stage 1 overrides these variables with a case equilibrium so its
    % evaluation interval does not include the source speed loop's long
    % operating-point acquisition transient.
    mw.assignin('stage1_speed_initial_revps', 0);
    mw.assignin('stage1_omega_m_initial_radps', 0);
    mw.assignin('stage1_speed_pi_initial_A', 0);
    mw.assignin('stage1_idq_initial_A', [0 0]);
    mw.assignin('stage1_load_torque_Nm', 0);
end

function local_parameterize_operating_point(model)
loadBlock = [model '/Constant16'];
assert(getSimulinkBlockHandle(loadBlock) > 0, ...
    'Stage1:MissingLoadBlock', 'Expected load block not found.');
set_param(loadBlock, 'Value', 'stage1_load_torque_Nm');

steps = find_system(model, 'SearchDepth', 1, 'BlockType', 'Step');
activeStep = '';
for k = 1:numel(steps)
    ports = get_param(steps{k}, 'PortHandles');
    lineHandle = get_param(ports.Outport, 'Line');
    if lineHandle == -1
        continue;
    end
    destinations = get_param(lineHandle, 'DstBlockHandle');
    for j = 1:numel(destinations)
        if destinations(j) == -1
            continue;
        end
        destinationName = get_param(destinations(j), 'Name');
        if contains(destinationName, 'Rate Limiter2')
            activeStep = steps{k};
            break;
        end
    end
    if ~isempty(activeStep)
        break;
    end
end
assert(~isempty(activeStep), 'Stage1:MissingSpeedStep', ...
    'Could not locate the closed-loop speed step.');
    set_param(activeStep, ...
        'Before', 'stage1_speed_initial_revps', ...
        'After', 'stage1_speed_target_rpm');

    rateLimiter = [model '/Discrete Rate Limiter2'];
    assert(getSimulinkBlockHandle(rateLimiter) > 0, ...
        'Stage1:MissingSpeedRateLimiter', ...
        'Expected active speed rate limiter not found.');
    set_param(rateLimiter, 'Vinit', 'stage1_speed_initial_revps');

    plant = [model '/Surface Mount PMSM'];
    assert(getSimulinkBlockHandle(plant) > 0, ...
        'Stage1:MissingPlant', 'Expected PMSM plant not found.');
    set_param(plant, ...
        'omega_init', 'stage1_omega_m_initial_radps', ...
        'idq0', 'stage1_idq_initial_A');

    speedPi = [model '/PID Controller2'];
    assert(getSimulinkBlockHandle(speedPi) > 0, ...
        'Stage1:MissingSpeedPI', 'Expected speed PI not found.');
    set_param(speedPi, 'InitialConditionForIntegrator', ...
        'stage1_speed_pi_initial_A');
end

function local_install_encoder_forward_model(model)
encoder = [model '/Position_Sensing_Encoder'];
assert(getSimulinkBlockHandle(encoder) > 0, ...
    'Stage1:MissingEncoder', 'Position_Sensing_Encoder was not found.');

% Keep the original legacy path byte-for-behavior at block level:
% theta_raw -> theta_offset -> theta_quantizer.  Only replace the line from
% theta_quantizer to theta_sensed with a sensor-mode switch.
legacyQuantizer = [encoder '/theta_quantizer'];
local_delete_output_line(legacyQuantizer);

add_block('simulink/Ports & Subsystems/In1', ...
    [encoder '/theta_m_true'], ...
    'Port', '3', 'Position', [25 250 55 270]);

add_block('simulink/Sources/Constant', [encoder '/Sensor_Mode'], ...
    'Value', 'sensor_mode', 'OutDataTypeStr', 'uint8', ...
    'Position', [515 270 575 300]);
add_block('simulink/Sources/Constant', [encoder '/Error_Mode'], ...
    'Value', 'encoder_error_mode', 'OutDataTypeStr', 'uint8', ...
    'Position', [175 385 235 415]);
add_block('simulink/Sources/Constant', [encoder '/Zero_Error'], ...
    'Value', '0', 'Position', [175 455 235 485]);
add_block('simulink/Sources/Constant', [encoder '/Fixed_Error'], ...
    'Value', 'encoder_error_bias_m_rad', ...
    'Position', [175 425 235 445]);
add_block('simulink/User-Defined Functions/Fcn', ...
    [encoder '/Periodic_Error'], ...
    'Expr', ['encoder_error_bias_m_rad + ' ...
        'encoder_error_amp1_m_rad*sin(u+encoder_error_phase1_rad) + ' ...
        'encoder_error_amp2_m_rad*sin(2*u+encoder_error_phase2_rad)'], ...
    'Position', [170 305 350 340]);
add_block('simulink/Signal Routing/Switch', ...
    [encoder '/Select_Off_Or_Fixed'], ...
    'Criteria', 'u2 >= Threshold', 'Threshold', '1', ...
    'Position', [285 420 325 485]);
add_block('simulink/Signal Routing/Switch', ...
    [encoder '/Select_Error_Mode'], ...
    'Criteria', 'u2 >= Threshold', 'Threshold', '2', ...
    'Position', [385 345 425 415]);

add_block('simulink/Sources/Random Number', ...
    [encoder '/Encoder_Angle_Noise'], ...
    'Mean', '0', 'Variance', 'encoder_noise_std_m_rad^2', ...
    'Seed', 'double(encoder_noise_seed)', ...
    'SampleTime', 'angle_sample_period_s', ...
    'Position', [385 455 455 485]);
add_block('simulink/Math Operations/Sum', ...
    [encoder '/Apply_Mechanical_Error'], ...
    'Inputs', '+++', 'Position', [485 315 515 375]);
add_block('simulink/Math Operations/Math Function', ...
    [encoder '/Wrap_Mechanical_0_2pi'], ...
    'Operator', 'mod', 'Position', [545 325 655 365]);
add_block('simulink/Sources/Constant', ...
    [encoder '/Mechanical_Wrap_Modulus'], ...
    'Value', '2*pi', 'Position', [545 385 605 415]);
add_block('simulink/Discontinuities/Quantizer', ...
    [encoder '/Mechanical_Encoder_Quantizer'], ...
    'QuantizationInterval', '2*pi/encoder_counts_per_rev', ...
    'Position', [685 325 795 365]);
add_block('simulink/Discrete/Zero-Order Hold', ...
    [encoder '/Mechanical_Angle_Timestamp'], ...
    'SampleTime', 'angle_sample_period_s', ...
    'Position', [825 325 925 365]);
add_block('simulink/Discrete/Zero-Order Hold', ...
    [encoder '/Injected_Error_Timestamp'], ...
    'SampleTime', 'angle_sample_period_s', ...
    'Position', [685 400 795 440]);
add_block('simulink/Math Operations/Gain', ...
    [encoder '/Mechanical_To_Electrical'], ...
    'Gain', 'pn', 'Position', [950 325 1000 365]);
add_block('simulink/Math Operations/Bias', ...
    [encoder '/Electrical_Zero_Offset'], ...
    'Bias', 'theta0_e_rad', 'Position', [1025 325 1100 365]);

add_block('simulink/Signal Routing/Switch', ...
    [encoder '/Select_Sensor_Mode_Electrical'], ...
    'Criteria', 'u2 >= Threshold', 'Threshold', '1', ...
    'Position', [1135 155 1180 230]);
add_block('simulink/Math Operations/Gain', ...
    [encoder '/Legacy_Electrical_To_Mechanical'], ...
    'Gain', '1/pn', 'Position', [780 90 860 120]);
add_block('simulink/Signal Routing/Switch', ...
    [encoder '/Select_Sensor_Mode_Mechanical'], ...
    'Criteria', 'u2 >= Threshold', 'Threshold', '1', ...
    'Position', [1135 285 1180 360]);
add_block('simulink/Signal Routing/Switch', ...
    [encoder '/Select_Sensor_Mode_Error'], ...
    'Criteria', 'u2 >= Threshold', 'Threshold', '1', ...
    'Position', [1135 400 1180 465]);
add_block('simulink/Ports & Subsystems/Out1', ...
    [encoder '/theta_m_raw'], 'Port', '3', ...
    'Position', [1235 320 1265 340]);
add_block('simulink/Ports & Subsystems/Out1', ...
    [encoder '/injected_error_m'], 'Port', '4', ...
    'Position', [1235 425 1265 445]);

add_line(encoder, 'theta_m_true/1', 'Periodic_Error/1', 'autorouting', 'on');
add_line(encoder, 'theta_m_true/1', 'Apply_Mechanical_Error/1', 'autorouting', 'on');
add_line(encoder, 'Fixed_Error/1', 'Select_Off_Or_Fixed/1', 'autorouting', 'on');
add_line(encoder, 'Error_Mode/1', 'Select_Off_Or_Fixed/2', 'autorouting', 'on');
add_line(encoder, 'Zero_Error/1', 'Select_Off_Or_Fixed/3', 'autorouting', 'on');
add_line(encoder, 'Periodic_Error/1', 'Select_Error_Mode/1', 'autorouting', 'on');
add_line(encoder, 'Error_Mode/1', 'Select_Error_Mode/2', 'autorouting', 'on');
add_line(encoder, 'Select_Off_Or_Fixed/1', 'Select_Error_Mode/3', 'autorouting', 'on');
add_line(encoder, 'Select_Error_Mode/1', 'Apply_Mechanical_Error/2', 'autorouting', 'on');
add_line(encoder, 'Encoder_Angle_Noise/1', 'Apply_Mechanical_Error/3', 'autorouting', 'on');
add_line(encoder, 'Apply_Mechanical_Error/1', 'Wrap_Mechanical_0_2pi/1', 'autorouting', 'on');
add_line(encoder, 'Mechanical_Wrap_Modulus/1', 'Wrap_Mechanical_0_2pi/2', 'autorouting', 'on');
add_line(encoder, 'Wrap_Mechanical_0_2pi/1', 'Mechanical_Encoder_Quantizer/1', 'autorouting', 'on');
add_line(encoder, 'Mechanical_Encoder_Quantizer/1', 'Mechanical_Angle_Timestamp/1', 'autorouting', 'on');
add_line(encoder, 'Select_Error_Mode/1', 'Injected_Error_Timestamp/1', 'autorouting', 'on');
add_line(encoder, 'Mechanical_Angle_Timestamp/1', 'Mechanical_To_Electrical/1', 'autorouting', 'on');
add_line(encoder, 'Mechanical_To_Electrical/1', 'Electrical_Zero_Offset/1', 'autorouting', 'on');

add_line(encoder, 'Electrical_Zero_Offset/1', 'Select_Sensor_Mode_Electrical/1', 'autorouting', 'on');
add_line(encoder, 'Sensor_Mode/1', 'Select_Sensor_Mode_Electrical/2', 'autorouting', 'on');
add_line(encoder, 'theta_quantizer/1', 'Select_Sensor_Mode_Electrical/3', 'autorouting', 'on');
add_line(encoder, 'Select_Sensor_Mode_Electrical/1', 'theta_sensed/1', 'autorouting', 'on');

add_line(encoder, 'theta_quantizer/1', 'Legacy_Electrical_To_Mechanical/1', 'autorouting', 'on');
add_line(encoder, 'Mechanical_Angle_Timestamp/1', 'Select_Sensor_Mode_Mechanical/1', 'autorouting', 'on');
add_line(encoder, 'Sensor_Mode/1', 'Select_Sensor_Mode_Mechanical/2', 'autorouting', 'on');
add_line(encoder, 'Legacy_Electrical_To_Mechanical/1', 'Select_Sensor_Mode_Mechanical/3', 'autorouting', 'on');
add_line(encoder, 'Select_Sensor_Mode_Mechanical/1', 'theta_m_raw/1', 'autorouting', 'on');

add_line(encoder, 'Injected_Error_Timestamp/1', 'Select_Sensor_Mode_Error/1', 'autorouting', 'on');
add_line(encoder, 'Sensor_Mode/1', 'Select_Sensor_Mode_Error/2', 'autorouting', 'on');
add_line(encoder, 'Zero_Error/1', 'Select_Sensor_Mode_Error/3', 'autorouting', 'on');
add_line(encoder, 'Select_Sensor_Mode_Error/1', 'injected_error_m/1', 'autorouting', 'on');

% Feed the true mechanical rotor angle (MtrPos) into the added encoder port.
busSelector = find_system(model, 'SearchDepth', 1, 'BlockType', 'BusSelector');
assert(isscalar(busSelector), 'Stage1:AmbiguousMotorBus', ...
    'Expected exactly one top-level BusSelector.');
busPorts = get_param(busSelector{1}, 'PortHandles');
encoderPorts = get_param(encoder, 'PortHandles');
assert(numel(busPorts.Outport) >= 6 && numel(encoderPorts.Inport) >= 3, ...
    'Stage1:MotorBusContractChanged', ...
    'MtrPos output or new encoder input is unavailable.');
add_line(model, busPorts.Outport(6), encoderPorts.Inport(3), 'autorouting', 'on');

Simulink.BlockDiagram.arrangeSystem(encoder, 'FullLayout', 'true');
end

function iabcMux = local_install_iabc_mux(model)
iabcMux = [model '/Stage1_iabc_meas_mux'];
add_block('simulink/Signal Routing/Mux', iabcMux, ...
    'Inputs', '3', 'Position', [1660 780 1665 850]);
currentBlocks = { ...
    [model '/Current_Sensing_ADC_Latency_Ia'], ...
    [model '/Current_Sensing_ADC_Latency_Ib'], ...
    [model '/Current_Sensing_ADC_Latency_Ic']};
for k = 1:3
    local_branch_to_port(model, currentBlocks{k}, 1, iabcMux, k);
end
end

function dutyBlock = local_install_duty_nonideal(model, iabcMux)
dutyBlock = [model '/Stage1_Duty_Nonideal'];
add_block('simulink/Ports & Subsystems/Subsystem', dutyBlock, ...
    'Position', [1500 610 1690 720]);
local_delete_template_ports(dutyBlock);

add_block('simulink/Ports & Subsystems/In1', [dutyBlock '/duty_cmd'], ...
    'Port', '1', 'Position', [25 55 55 75]);
add_block('simulink/Ports & Subsystems/In1', [dutyBlock '/iabc_meas'], ...
    'Port', '2', 'Position', [25 120 55 140]);
% Dead-time polarity is an interval property.  The measured-current path
% otherwise runs at the inherited 5-us base step, which would make the
% effective duty change inside a 50-us PWM interval while the observer
% records only one value.  Freeze the polarity input at the PWM boundary
% so duty_effective and min_pulse_flag are genuinely interval-effective.
add_block('simulink/Discrete/Zero-Order Hold', ...
    [dutyBlock '/iabc_at_pwm_boundary'], ...
    'SampleTime', '[T_ident 0]', ...
    'Position', [90 110 190 150]);
add_block('simulink/Sources/Constant', [dutyBlock '/min_pulse_duty'], ...
    'Value', 'pwm_min_pulse_duty', 'Position', [75 180 155 210]);
add_block('simulink/Sources/Constant', [dutyBlock '/deadtime_s'], ...
    'Value', 'pwm_deadtime_s', 'Position', [75 225 155 255]);
add_block('simulink/Sources/Constant', [dutyBlock '/ident_period_s'], ...
    'Value', 'T_ident', 'Position', [75 270 155 300]);
add_block('simulink/Sources/Constant', [dutyBlock '/duty_min'], ...
    'Value', 'pwm_min_duty', 'Position', [75 315 155 345]);
add_block('simulink/Sources/Constant', [dutyBlock '/duty_max'], ...
    'Value', 'pwm_max_duty', 'Position', [75 360 155 390]);

algorithm = [dutyBlock '/Apply_Duty_Nonidealities'];
add_block('simulink/User-Defined Functions/MATLAB Function', algorithm, ...
    'Position', [250 85 470 300]);
root = sfroot;
chart = root.find('-isa', 'Stateflow.EMChart', 'Path', algorithm);
assert(isscalar(chart), 'Stage1:DutyAlgorithmCreationFailed', ...
    'Could not create the duty nonideality MATLAB Function.');
chart.Script = sprintf([ ...
    'function [duty_eff,min_pulse_flag] = f(duty_cmd,iabc,min_pulse,deadtime_s,ident_period_s,duty_min,duty_max)\n' ...
    'duty_eff = duty_cmd;\n' ...
    'min_pulse_flag = false;\n' ...
    'for k = 1:3\n' ...
    '    d = duty_cmd(k);\n' ...
    '    if (d > duty_min) && (d < duty_min + min_pulse)\n' ...
    '        duty_eff(k) = duty_min;\n' ...
    '        min_pulse_flag = true;\n' ...
    '    elseif (d < duty_max) && (d > duty_max - min_pulse)\n' ...
    '        duty_eff(k) = duty_max;\n' ...
    '        min_pulse_flag = true;\n' ...
    '    end\n' ...
    'end\n' ...
    'dead_fraction = deadtime_s / ident_period_s;\n' ...
    'for k = 1:3\n' ...
    '    duty_eff(k) = duty_eff(k) - dead_fraction*sign(iabc(k));\n' ...
    '    duty_eff(k) = min(max(duty_eff(k),duty_min),duty_max);\n' ...
    'end\n' ...
    'end\n']);

add_block('simulink/Ports & Subsystems/Out1', ...
    [dutyBlock '/duty_effective'], 'Port', '1', ...
    'Position', [550 120 580 140]);
add_block('simulink/Ports & Subsystems/Out1', ...
    [dutyBlock '/min_pulse_flag'], 'Port', '2', ...
    'Position', [550 205 580 225]);

add_line(dutyBlock, 'duty_cmd/1', 'Apply_Duty_Nonidealities/1', 'autorouting', 'on');
add_line(dutyBlock, 'iabc_meas/1', 'iabc_at_pwm_boundary/1', 'autorouting', 'on');
add_line(dutyBlock, 'iabc_at_pwm_boundary/1', ...
    'Apply_Duty_Nonidealities/2', 'autorouting', 'on');
add_line(dutyBlock, 'min_pulse_duty/1', 'Apply_Duty_Nonidealities/3', 'autorouting', 'on');
add_line(dutyBlock, 'deadtime_s/1', 'Apply_Duty_Nonidealities/4', 'autorouting', 'on');
add_line(dutyBlock, 'ident_period_s/1', 'Apply_Duty_Nonidealities/5', 'autorouting', 'on');
add_line(dutyBlock, 'duty_min/1', 'Apply_Duty_Nonidealities/6', 'autorouting', 'on');
add_line(dutyBlock, 'duty_max/1', 'Apply_Duty_Nonidealities/7', 'autorouting', 'on');
add_block('simulink/Signal Routing/Demux', ...
    [dutyBlock '/effective_duty_demux'], ...
    'Outputs', '3', 'Position', [475 80 480 165]);
add_block('simulink/Signal Routing/Mux', ...
    [dutyBlock '/effective_duty_1d'], ...
    'Inputs', '3', 'Position', [515 80 520 165]);
add_line(dutyBlock, 'Apply_Duty_Nonidealities/1', ...
    'effective_duty_demux/1', 'autorouting', 'on');
add_line(dutyBlock, 'effective_duty_demux/1', ...
    'effective_duty_1d/1', 'autorouting', 'on');
add_line(dutyBlock, 'effective_duty_demux/2', ...
    'effective_duty_1d/2', 'autorouting', 'on');
add_line(dutyBlock, 'effective_duty_demux/3', ...
    'effective_duty_1d/3', 'autorouting', 'on');
add_line(dutyBlock, 'effective_duty_1d/1', ...
    'duty_effective/1', 'autorouting', 'on');
add_line(dutyBlock, 'Apply_Duty_Nonidealities/2', 'min_pulse_flag/1', 'autorouting', 'on');

averageInverter = [model '/Average-Value Inverter'];
averagePorts = get_param(averageInverter, 'PortHandles');
local_delete_input_line_handle(averagePorts.Inport(1));
local_branch_to_port(model, [model '/PWM_and_Actuation'], 1, dutyBlock, 1);
local_branch_to_port(model, iabcMux, 1, dutyBlock, 2);
dutyPorts = get_param(dutyBlock, 'PortHandles');
add_line(model, dutyPorts.Outport(1), averagePorts.Inport(1), 'autorouting', 'on');

Simulink.BlockDiagram.arrangeSystem(dutyBlock, 'FullLayout', 'true');
end

function voltageBlock = local_install_voltage_drop(model, iabcMux)
voltageBlock = [model '/Stage1_Voltage_Drop'];
add_block('simulink/Ports & Subsystems/Subsystem', voltageBlock, ...
    'Position', [1725 610 1890 720]);
local_delete_template_ports(voltageBlock);

add_block('simulink/Ports & Subsystems/In1', [voltageBlock '/vabc_ideal'], ...
    'Port', '1', 'Position', [25 60 55 80]);
add_block('simulink/Ports & Subsystems/In1', [voltageBlock '/iabc_meas'], ...
    'Port', '2', 'Position', [25 135 55 155]);
% Use the same boundary-held current polarity as the duty nonideality.
% This keeps plant-applied voltage constant over the represented PWM
% interval, so the +5-us observer sample denotes that complete interval.
add_block('simulink/Discrete/Zero-Order Hold', ...
    [voltageBlock '/iabc_at_pwm_boundary'], ...
    'SampleTime', '[T_ident 0]', ...
    'Position', [80 125 180 165]);
add_block('simulink/Math Operations/Sign', [voltageBlock '/current_sign'], ...
    'Position', [215 125 265 165]);
add_block('simulink/Math Operations/Gain', [voltageBlock '/device_drop'], ...
    'Gain', 'inverter_voltage_drop_V', ...
    'Position', [300 125 380 165]);
add_block('simulink/Math Operations/Sum', [voltageBlock '/apply_drop'], ...
    'Inputs', '+-', 'Position', [420 65 455 145]);
add_block('simulink/Ports & Subsystems/Out1', [voltageBlock '/vabc_plant'], ...
    'Port', '1', 'Position', [500 90 530 110]);
add_line(voltageBlock, 'vabc_ideal/1', 'apply_drop/1', 'autorouting', 'on');
add_line(voltageBlock, 'iabc_meas/1', 'iabc_at_pwm_boundary/1', 'autorouting', 'on');
add_line(voltageBlock, 'iabc_at_pwm_boundary/1', ...
    'current_sign/1', 'autorouting', 'on');
add_line(voltageBlock, 'current_sign/1', 'device_drop/1', 'autorouting', 'on');
add_line(voltageBlock, 'device_drop/1', 'apply_drop/2', 'autorouting', 'on');
add_line(voltageBlock, 'apply_drop/1', 'vabc_plant/1', 'autorouting', 'on');

plant = [model '/Surface Mount PMSM'];
plantPorts = get_param(plant, 'PortHandles');
local_delete_input_line_handle(plantPorts.Inport(2));
local_branch_to_port(model, [model '/Inverter_Nonideal'], 1, voltageBlock, 1);
local_branch_to_port(model, iabcMux, 1, voltageBlock, 2);
voltagePorts = get_param(voltageBlock, 'PortHandles');
add_line(model, voltagePorts.Outport(1), plantPorts.Inport(2), 'autorouting', 'on');

Simulink.BlockDiagram.arrangeSystem(voltageBlock, 'FullLayout', 'true');
end

function logNames = local_install_observer_taps(model, iabcMux, dutyNonideal, plantVoltage)
observer = [model '/Stage1_Observer_Taps'];
add_block('simulink/Ports & Subsystems/Subsystem', observer, ...
    'Position', [1880 780 2150 1140]);
local_delete_template_ports(observer);

inNames = { ...
    'iabc_meas', ...
    'duty_applied', ...
    'vdc', ...
    'theta_m_raw', ...
    'theta_re', ...
    'theta_m_true', ...
    'theta_e_true', ...
    'omega_m_true', ...
    'vabc_plant', ...
    'iq_ref', ...
    'duty_pre_sat', ...
    'encoder_error_m', ...
    'omega_m_sensed', ...
    'min_pulse_flag', ...
    'duty_saturated'};
logNames = strcat('stage1_', inNames);

for k = 1:numel(inNames)
    y = 25 + (k-1)*45;
    add_block('simulink/Ports & Subsystems/In1', ...
        [observer '/' inNames{k}], ...
        'Port', num2str(k), 'Position', [25 y 55 y+20]);
    add_block('simulink/Discrete/Zero-Order Hold', ...
        [observer '/' inNames{k} '_sample'], ...
        'SampleTime', '[T_ident stage1_ident_phase_s]', ...
        'Position', [105 y-5 200 y+25]);
    add_block('simulink/Sinks/To Workspace', ...
        [observer '/' inNames{k} '_log'], ...
        'VariableName', logNames{k}, ...
        'SaveFormat', 'Timeseries', ...
        'Position', [250 y-5 365 y+25]);
    if k ~= 1
        add_line(observer, [inNames{k} '/1'], ...
            [inNames{k} '_sample/1'], 'autorouting', 'on');
    end
    add_line(observer, [inNames{k} '_sample/1'], ...
        [inNames{k} '_log/1'], 'autorouting', 'on');
end

% Observer-only phase-current noise.  It never feeds the controller or
% truth path.  Independent deterministic seeds make the three phases
% reproducible while stage1_current_noise_std_A=0 is exactly transparent.
add_block('simulink/Sources/Random Number', [observer '/current_noise_a'], ...
    'Mean', '0', 'Variance', 'stage1_current_noise_std_A^2', ...
    'Seed', 'double(stage1_current_noise_seed)', ...
    'SampleTime', 'T_ident', 'Position', [410 25 500 55]);
add_block('simulink/Sources/Random Number', [observer '/current_noise_b'], ...
    'Mean', '0', 'Variance', 'stage1_current_noise_std_A^2', ...
    'Seed', 'double(stage1_current_noise_seed)+1', ...
    'SampleTime', 'T_ident', 'Position', [410 65 500 95]);
add_block('simulink/Sources/Random Number', [observer '/current_noise_c'], ...
    'Mean', '0', 'Variance', 'stage1_current_noise_std_A^2', ...
    'Seed', 'double(stage1_current_noise_seed)+2', ...
    'SampleTime', 'T_ident', 'Position', [410 105 500 135]);
add_block('simulink/Signal Routing/Mux', [observer '/current_noise_mux'], ...
    'Inputs', '3', 'Position', [545 30 550 130]);
add_block('simulink/Math Operations/Sum', [observer '/apply_current_noise'], ...
    'Inputs', '++', 'Position', [600 50 635 105]);
add_line(observer, 'current_noise_a/1', 'current_noise_mux/1', 'autorouting', 'on');
add_line(observer, 'current_noise_b/1', 'current_noise_mux/2', 'autorouting', 'on');
add_line(observer, 'current_noise_c/1', 'current_noise_mux/3', 'autorouting', 'on');
add_line(observer, 'iabc_meas/1', 'apply_current_noise/1', 'autorouting', 'on');
add_line(observer, 'current_noise_mux/1', 'apply_current_noise/2', 'autorouting', 'on');
add_line(observer, 'apply_current_noise/1', 'iabc_meas_sample/1', 'autorouting', 'on');

% Overmodulation is derived from aligned pre-saturation and saturated PWM
% command.  It deliberately excludes deadtime/min-pulse modifications in
% duty_effective, which have their own validity semantics.
add_block('simulink/Math Operations/Sum', [observer '/duty_delta'], ...
    'Inputs', '+-', 'Position', [430 115 460 170]);
add_block('simulink/Math Operations/Abs', [observer '/duty_delta_abs'], ...
    'Position', [495 125 535 160]);
add_block('simulink/Logic and Bit Operations/Compare To Constant', ...
    [observer '/duty_clipped_elements'], ...
    'const', 'stage1_overmod_epsilon', 'relop', '>', ...
    'Position', [575 120 705 165]);
add_block('simulink/Logic and Bit Operations/Logical Operator', ...
    [observer '/any_duty_clipped'], ...
    'Operator', 'OR', 'Inputs', '1', ...
    'Position', [745 120 800 165]);
add_block('simulink/Discrete/Zero-Order Hold', ...
    [observer '/overmod_flag_sample'], ...
    'SampleTime', '[T_ident stage1_ident_phase_s]', ...
    'Position', [845 120 945 165]);
add_block('simulink/Sinks/To Workspace', ...
    [observer '/overmod_flag_log'], ...
    'VariableName', 'stage1_overmod_flag', ...
    'SaveFormat', 'Timeseries', ...
    'Position', [990 120 1110 165]);
add_line(observer, 'duty_pre_sat_sample/1', 'duty_delta/1', 'autorouting', 'on');
add_line(observer, 'duty_saturated_sample/1', 'duty_delta/2', 'autorouting', 'on');
add_line(observer, 'duty_delta/1', 'duty_delta_abs/1', 'autorouting', 'on');
add_line(observer, 'duty_delta_abs/1', 'duty_clipped_elements/1', 'autorouting', 'on');
add_line(observer, 'duty_clipped_elements/1', 'any_duty_clipped/1', 'autorouting', 'on');
add_line(observer, 'any_duty_clipped/1', 'overmod_flag_sample/1', 'autorouting', 'on');
add_line(observer, 'overmod_flag_sample/1', 'overmod_flag_log/1', 'autorouting', 'on');

add_block('simulink/Sources/Clock', [observer '/ident_clock'], ...
    'Position', [430 225 465 255]);
add_block('simulink/Discrete/Zero-Order Hold', ...
    [observer '/timestamp_sample'], ...
    'SampleTime', '[T_ident stage1_ident_phase_s]', ...
    'Position', [510 220 610 260]);
add_block('simulink/Sinks/To Workspace', ...
    [observer '/timestamp_log'], ...
    'VariableName', 'stage1_timestamp_s', ...
    'SaveFormat', 'Timeseries', ...
    'Position', [650 220 770 260]);
add_line(observer, 'ident_clock/1', 'timestamp_sample/1', 'autorouting', 'on');
add_line(observer, 'timestamp_sample/1', 'timestamp_log/1', 'autorouting', 'on');

add_block('simulink/Math Operations/Abs', [observer '/current_abs'], ...
    'Position', [430 300 475 335]);
add_block('simulink/Logic and Bit Operations/Compare To Constant', ...
    [observer '/current_in_adc_range'], ...
    'const', 'adc_current_range_A', 'relop', '<', ...
    'Position', [510 295 640 340]);
add_block('simulink/Logic and Bit Operations/Logical Operator', ...
    [observer '/all_currents_valid'], ...
    'Operator', 'AND', 'Inputs', '1', ...
    'Position', [680 295 735 340]);
add_block('simulink/Discrete/Zero-Order Hold', ...
    [observer '/valid_sample'], ...
    'SampleTime', '[T_ident stage1_ident_phase_s]', ...
    'Position', [775 300 875 340]);
add_block('simulink/Sinks/To Workspace', ...
    [observer '/valid_log'], ...
    'VariableName', 'stage1_valid', ...
    'SaveFormat', 'Timeseries', ...
    'Position', [915 300 1035 340]);
add_line(observer, 'iabc_meas_sample/1', 'current_abs/1', 'autorouting', 'on');
add_line(observer, 'current_abs/1', 'current_in_adc_range/1', 'autorouting', 'on');
add_line(observer, 'current_in_adc_range/1', 'all_currents_valid/1', 'autorouting', 'on');
add_line(observer, 'all_currents_valid/1', 'valid_sample/1', 'autorouting', 'on');
add_line(observer, 'valid_sample/1', 'valid_log/1', 'autorouting', 'on');

logNames = [logNames, {'stage1_overmod_flag', ...
    'stage1_timestamp_s', 'stage1_valid'}];

% Raw observer-source buses.  These deliberately contain only signals that
% already exist inside the copied Simulink model.  They are not the formal
% Stage-1 IdentificationBus/EvaluationTruthBus: the analysis layer adds the
% derived unwrapped angle, speed estimate, direction state, aligned
% timestamps, electrical truth quantities, and plant dq voltage before
% publishing those complete interfaces.  The raw truth-source bus is
% sink-only.
identSources = { ...
    'iabc_meas_sample', 'duty_applied_sample', 'vdc_sample', ...
    'theta_m_raw_sample', 'theta_re_sample', 'duty_pre_sat_sample', ...
    'overmod_flag_sample', 'min_pulse_flag_sample', ...
    'valid_sample', 'timestamp_sample'};
identFields = { ...
    'iabc_meas_A', 'duty_applied', 'vdc_V', 'theta_m_raw_rad', ...
    'theta_e_raw_rad', 'duty_pre_sat', 'pwm_overmodulated', ...
    'min_pulse_clipped', 'valid', 'timestamp_s'};
add_block('simulink/Signal Routing/Bus Creator', ...
    [observer '/RawIdentificationSourceBus_Creator'], ...
    'Inputs', num2str(numel(identSources)), ...
    'Position', [1180 80 1185 330]);
for k = 1:numel(identSources)
    lineHandle = add_line(observer, [identSources{k} '/1'], ...
        sprintf('RawIdentificationSourceBus_Creator/%d', k), 'autorouting', 'on');
    set_param(lineHandle, 'Name', identFields{k});
end
add_block('simulink/Sinks/To Workspace', ...
    [observer '/raw_identification_source_bus_log'], ...
    'VariableName', 'stage1_raw_identification_source_bus', ...
    'SaveFormat', 'Dataset', 'Position', [1245 175 1390 215]);
add_line(observer, 'RawIdentificationSourceBus_Creator/1', ...
    'raw_identification_source_bus_log/1', 'autorouting', 'on');

truthSources = { ...
    'theta_m_true_sample', 'theta_e_true_sample', ...
    'omega_m_true_sample', 'encoder_error_m_sample', ...
    'vabc_plant_sample', 'omega_m_sensed_sample'};
truthFields = { ...
    'theta_m_true_rad', 'theta_e_true_rad', 'omega_m_true_radps', ...
    'encoder_error_m_rad', 'vabc_plant_V', 'omega_m_sensor_truth_radps'};
add_block('simulink/Signal Routing/Bus Creator', ...
    [observer '/RawEvaluationTruthSourceBus_Creator'], ...
    'Inputs', num2str(numel(truthSources)), ...
    'Position', [1180 400 1185 600]);
for k = 1:numel(truthSources)
    lineHandle = add_line(observer, [truthSources{k} '/1'], ...
        sprintf('RawEvaluationTruthSourceBus_Creator/%d', k), 'autorouting', 'on');
    set_param(lineHandle, 'Name', truthFields{k});
end
add_block('simulink/Sinks/To Workspace', ...
    [observer '/raw_evaluation_truth_source_bus_log'], ...
    'VariableName', 'stage1_raw_evaluation_truth_source_bus', ...
    'SaveFormat', 'Dataset', 'Position', [1245 480 1390 520]);
add_line(observer, 'RawEvaluationTruthSourceBus_Creator/1', ...
    'raw_evaluation_truth_source_bus_log/1', 'autorouting', 'on');
logNames = [logNames, {'stage1_raw_identification_source_bus', ...
    'stage1_raw_evaluation_truth_source_bus'}];

observerPorts = get_param(observer, 'PortHandles');
local_connect_handles(model, get_param(iabcMux, 'PortHandles'), 1, observerPorts, 1);
dutyPorts = get_param(dutyNonideal, 'PortHandles');
add_line(model, dutyPorts.Outport(1), observerPorts.Inport(2), 'autorouting', 'on');
local_branch_to_observer(model, [model '/Constant8'], 1, observerPorts.Inport(3));

encoderPorts = get_param([model '/Position_Sensing_Encoder'], 'PortHandles');
add_line(model, encoderPorts.Outport(3), observerPorts.Inport(4), 'autorouting', 'on');
local_branch_to_observer(model, [model '/Position_Sensing_Encoder_Latency_Theta'], 1, observerPorts.Inport(5));

busSelector = find_system(model, 'SearchDepth', 1, 'BlockType', 'BusSelector');
busPorts = get_param(busSelector{1}, 'PortHandles');
add_line(model, busPorts.Outport(6), observerPorts.Inport(6), 'autorouting', 'on');

thetaGoto = find_system(model, 'SearchDepth', 1, ...
    'BlockType', 'Goto', 'GotoTag', 'thetae');
assert(isscalar(thetaGoto), 'Stage1:AmbiguousThetaTruth', ...
    'Expected one thetae Goto block.');
thetaGotoConnectivity = get_param(thetaGoto{1}, 'PortConnectivity');
thetaTruthSource = thetaGotoConnectivity(1).SrcBlock;
thetaTruthPort = thetaGotoConnectivity(1).SrcPort + 1;
thetaTruthPorts = get_param(thetaTruthSource, 'PortHandles');
add_line(model, thetaTruthPorts.Outport(thetaTruthPort), ...
    observerPorts.Inport(7), 'autorouting', 'on');

add_line(model, busPorts.Outport(1), observerPorts.Inport(8), 'autorouting', 'on');
voltagePorts = get_param(plantVoltage, 'PortHandles');
add_line(model, voltagePorts.Outport(1), observerPorts.Inport(9), 'autorouting', 'on');
local_branch_to_observer(model, [model '/Sum3'], 1, observerPorts.Inport(10));
local_branch_to_observer(model, [model '/Mux2'], 1, observerPorts.Inport(11));
add_line(model, encoderPorts.Outport(4), observerPorts.Inport(12), 'autorouting', 'on');
local_branch_to_observer(model, [model '/Position_Sensing_Encoder_Latency_Wm'], 1, observerPorts.Inport(13));
add_line(model, dutyPorts.Outport(2), observerPorts.Inport(14), 'autorouting', 'on');
local_branch_to_observer(model, [model '/PWM_and_Actuation'], 1, observerPorts.Inport(15));

Simulink.BlockDiagram.arrangeSystem(observer, 'FullLayout', 'true');
end

function local_branch_to_port(model, sourceBlock, sourcePort, destinationBlock, destinationPort)
sourcePorts = get_param(sourceBlock, 'PortHandles');
destinationPorts = get_param(destinationBlock, 'PortHandles');
add_line(model, sourcePorts.Outport(sourcePort), ...
    destinationPorts.Inport(destinationPort), 'autorouting', 'on');
end

function local_branch_to_observer(model, sourceBlock, sourcePort, destinationPortHandle)
sourcePorts = get_param(sourceBlock, 'PortHandles');
add_line(model, sourcePorts.Outport(sourcePort), destinationPortHandle, ...
    'autorouting', 'on');
end

function local_connect_handles(model, sourcePorts, sourcePort, destinationPorts, destinationPort)
add_line(model, sourcePorts.Outport(sourcePort), ...
    destinationPorts.Inport(destinationPort), 'autorouting', 'on');
end

function local_delete_output_line(block)
ports = get_param(block, 'PortHandles');
lineHandle = get_param(ports.Outport(1), 'Line');
if lineHandle ~= -1
    delete_line(lineHandle);
end
end

function local_delete_input_line_handle(inputPortHandle)
lineHandle = get_param(inputPortHandle, 'Line');
if lineHandle ~= -1
    delete_line(lineHandle);
end
end

function local_delete_template_ports(subsystem)
templateIn = [subsystem '/In1'];
templateOut = [subsystem '/Out1'];
if getSimulinkBlockHandle(templateIn) > 0
    delete_block(templateIn);
end
if getSimulinkBlockHandle(templateOut) > 0
    delete_block(templateOut);
end
end

function contract = local_solver_contract(model)
keys = {'SolverType', 'Solver', 'FixedStep', 'StartTime', 'StopTime', ...
    'SaveFormat', 'SaveTime', 'SaveOutput', 'SaveState', ...
    'SignalLogging', 'ReturnWorkspaceOutputs'};
contract = struct();
for k = 1:numel(keys)
    contract.(keys{k}) = get_param(model, keys{k});
end
end

function digestHex = local_sha256(filePath)
fid = fopen(filePath, 'rb');
assert(fid ~= -1, 'Stage1:HashReadFailed', ...
    'Could not open file for hashing: %s', filePath);
cleanupFile = onCleanup(@() fclose(fid));
bytes = fread(fid, inf, 'uint8=>uint8');
digest = java.security.MessageDigest.getInstance('SHA-256');
digest.update(typecast(bytes, 'int8'));
raw = typecast(digest.digest(), 'uint8');
digestHex = lower(reshape(dec2hex(raw, 2).', 1, []));
end

function local_close_without_saving(model)
if bdIsLoaded(model)
    close_system(model, 0);
end
end
