function [state,event] = scheme2_update_atan2_free(state,sample,cfg)
%SCHEME2_UPDATE_ATAN2_FREE Diagnostic E40 sine-error update without atan2.
%   This API accepts y_d/y_q but never accepts z or an entire trace.

s = local_stage4(cfg);
local_validate_sample(sample);
assert(state.source_mode == s.MODE_ATAN2_FREE, ...
    'anglelut:Scheme2SourceModeMismatch', ...
    'The atan2-free updater requires an atan2-free Scheme-2 state.');
sampleValid = logical(sample.valid) && isfinite(sample.phi_m_rad) && ...
    isfinite(sample.y_d_A) && isfinite(sample.y_q_A) && ...
    isfinite(sample.quality_weight) && sample.quality_weight > 0 && ...
    isfinite(sample.theta_m_unwrapped_rad) && ...
    isfinite(sample.timestamp_s);
rawSine = NaN;
clippedSine = NaN;
if sampleValid
    prediction = anglelut.periodic_lut_interp( ...
        sample.phi_m_rad,state.shadow_lut_e_rad);
    magnitude = sqrt(sample.y_d_A*sample.y_d_A + ...
        sample.y_q_A*sample.y_q_A + ...
        s.atan2_free_epsilon_A*s.atan2_free_epsilon_A);
    rawSine = (sample.y_d_A*cos(prediction)- ...
        sample.y_q_A*sin(prediction))/magnitude;
    sineLimit = sin(s.innovation_clip_e_rad);
    clippedSine = min(max(rawSine,-sineLimit),sineLimit);
end
[state,event] = anglelut.scheme2_apply_update(state, ...
    double(sample.phi_m_rad),clippedSine,rawSine,NaN, ...
    double(sample.quality_weight),double(sample.theta_m_unwrapped_rad), ...
    double(sample.timestamp_s),sampleValid,cfg);
end

function local_validate_sample(sample)
allowed = sort(["phi_m_rad","y_d_A","y_q_A","quality_weight", ...
    "theta_m_unwrapped_rad","timestamp_s","valid"]);
actual = sort(string(fieldnames(sample)).');
assert(isequal(actual,allowed),'anglelut:Scheme2Atan2FreeSampleSchema', ...
    'Scheme-2 atan2-free sample must contain only its seven-field whitelist.');
end

function s = local_stage4(cfg)
if isfield(cfg,'stage4'), s = cfg.stage4; else, s = cfg; end
end
