function [metrics,summary] = compute_stage2_learning_metrics(history,reference)
%COMPUTE_STAGE2_LEARNING_METRICS Score every saved Scheme-4 solve snapshot.
%   REFERENCE is evaluation-only. It is never passed back to the learner.

requiredHistory = {'solve_count','sample_index','time_s','travel_m_rad', ...
    'coverage_fraction','reference_relative_difference', ...
    'normal_equation_relative_residual','rcond', ...
    'active_update_rms_e_rad','shadow_lut_e_rad','active_lut_e_rad'};
assert(all(isfield(history,requiredHistory)), ...
    'anglelut:Stage2LearningHistorySchema','Learning history is incomplete.');
assert(isfield(reference,'lut_e_rad') && isfield(reference,'valid_mask'), ...
    'anglelut:Stage2LearningReferenceSchema', ...
    'Evaluation reference is incomplete.');

referenceLut = double(reference.lut_e_rad(:)).';
valid = logical(reference.valid_mask(:)).' & isfinite(referenceLut);
n = numel(history.solve_count);
assert(n >= 1 && size(history.shadow_lut_e_rad,1) == n && ...
    size(history.active_lut_e_rad,1) == n && ...
    size(history.active_lut_e_rad,2) == numel(referenceLut), ...
    'anglelut:Stage2LearningHistorySize','Learning history sizes disagree.');
baselineRmse = local_rms(anglelut.wrap_to_pi(-referenceLut(valid)));
shadowRmse = zeros(n,1);
activeRmse = zeros(n,1);
for k = 1:n
    shadowError = anglelut.wrap_to_pi( ...
        double(history.shadow_lut_e_rad(k,valid))-referenceLut(valid));
    activeError = anglelut.wrap_to_pi( ...
        double(history.active_lut_e_rad(k,valid))-referenceLut(valid));
    shadowRmse(k) = local_rms(shadowError);
    activeRmse(k) = local_rms(activeError);
end
improvement = 1-activeRmse/max(baselineRmse,eps);

metrics = table(double(history.solve_count(:)), ...
    double(history.sample_index(:)),double(history.time_s(:)), ...
    double(history.travel_m_rad(:))/(2*pi), ...
    double(history.coverage_fraction(:)),rad2deg(shadowRmse), ...
    rad2deg(activeRmse),100*improvement, ...
    rad2deg(double(history.active_update_rms_e_rad(:))), ...
    double(history.reference_relative_difference(:)), ...
    double(history.normal_equation_relative_residual(:)), ...
    double(history.rcond(:)), ...
    'VariableNames',{'solve_count','sample_index','time_s', ...
    'mechanical_cycles','coverage_fraction','shadow_rmse_e_deg', ...
    'active_rmse_e_deg','active_improvement_percent', ...
    'active_update_rms_e_deg','solver_relative_difference', ...
    'normal_equation_relative_residual','rcond'});

summary = struct('solve_count',n, ...
    'baseline_rmse_e_deg',rad2deg(baselineRmse), ...
    'first_active_rmse_e_deg',metrics.active_rmse_e_deg(1), ...
    'final_active_rmse_e_deg',metrics.active_rmse_e_deg(end), ...
    'first_shadow_rmse_e_deg',metrics.shadow_rmse_e_deg(1), ...
    'final_shadow_rmse_e_deg',metrics.shadow_rmse_e_deg(end), ...
    'first_improvement_percent',metrics.active_improvement_percent(1), ...
    'final_improvement_percent',metrics.active_improvement_percent(end), ...
    'active_rmse_monotonic_nonincreasing', ...
    all(diff(metrics.active_rmse_e_deg) <= 100*eps), ...
    'improvement_monotonic_nondecreasing', ...
    all(diff(metrics.active_improvement_percent) >= -100*eps), ...
    'evaluation_reference_only',true,'truth_feedback_used',false);
end

function value = local_rms(x)
if isempty(x), value = NaN; else, value = sqrt(mean(x.^2)); end
end
