function [metrics,trace] = evaluate_stage3_frozen(simOut,stage1Trace,c,cfg, ...
        activeEnable)
%EVALUATE_STAGE3_FROZEN Score a frozen Scheme-5 active-off/on simulation.

required = {'stage3_control_theta_e','stage3_lut_compensation_e', ...
    'stage3_torque_true_Nm','stage1_iabc_meas','stage1_theta_e_true', ...
    'stage1_iq_ref'};
for k = 1:numel(required)
    assert(any(strcmp(simOut.who,required{k})), ...
        'anglelut:MissingStage3Log','Missing Stage-3 log %s.',required{k});
end
controlLog = simOut.get('stage3_control_theta_e');
time_s = double(controlLog.Time(:));
controlTheta = local_sample(simOut,'stage3_control_theta_e',time_s);
compensation = local_sample(simOut,'stage3_lut_compensation_e',time_s);
torque = local_sample(simOut,'stage3_torque_true_Nm',time_s);
iabc = local_sample(simOut,'stage1_iabc_meas',time_s);
thetaTrue = local_sample(simOut,'stage1_theta_e_true',time_s);
iqRef = local_sample(simOut,'stage1_iq_ref',time_s);
if size(iabc,2) ~= 3, iabc = reshape(iabc,[],3); end
evaluation = time_s >= cfg.simulation.steady_state_time_s;
finite = evaluation & isfinite(controlTheta) & isfinite(thetaTrue) & ...
    isfinite(torque) & isfinite(iqRef) & all(isfinite(iabc),2);
id = zeros(numel(time_s),1); iq = id;
for k = 1:numel(time_s)
    iab = anglelut.clarke_abc(iabc(k,:).');
    idq = anglelut.park_alphabeta(iab,thetaTrue(k));
    id(k) = idq(1); iq(k) = idq(2);
end
controlError = anglelut.wrap_to_pi(controlTheta-thetaTrue);
residualMask = stage1Trace.valid & stage1Trace.evaluation_mask;
compResidual = sample_logged_signal( ...
    simOut.get('stage3_lut_compensation_e'),stage1Trace.time_s,'linear');
compResidual = double(compResidual(:,1));
fullResidual = anglelut.compensated_prediction_residual( ...
    stage1Trace.residual_A,stage1Trace.expected_amplitude_A, ...
    stage1Trace.direction_sign,compResidual);
residualMask = residualMask & all(isfinite(fullResidual),2);

metrics = struct('case_id',char(c.case_id),'active_enable',logical(activeEnable), ...
    'expected_class',local_class(c),'sample_count',nnz(finite), ...
    'control_angle_rmse_e_rad',local_rms(controlError(finite)), ...
    'id_rms_A',local_rms(id(finite)), ...
    'iq_tracking_rmse_A',local_rms(iq(finite)-iqRef(finite)), ...
    'prediction_residual_rms_A',local_rms(hypot( ...
    fullResidual(residualMask,1),fullResidual(residualMask,2))), ...
    'mean_torque_Nm',local_mean(torque(finite)), ...
    'compensation_rms_e_rad',local_rms(compensation(finite)), ...
    'compensation_max_abs_e_rad',local_max_abs(compensation(finite)));
metrics.control_angle_rmse_e_deg = rad2deg(metrics.control_angle_rmse_e_rad);
metrics.torque_ripple_rms_Nm = local_rms( ...
    torque(finite)-metrics.mean_torque_Nm);
trace = struct('time_s',time_s,'evaluation_mask',finite, ...
    'control_theta_e_rad',controlTheta,'truth_theta_e_rad',thetaTrue, ...
    'control_error_e_rad',controlError, ...
    'lut_compensation_e_rad',compensation,'id_A',id,'iq_A',iq, ...
    'iq_ref_A',iqRef,'torque_Nm',torque, ...
    'prediction_residual_A',fullResidual, ...
    'prediction_residual_mask',residualMask,'learning_frozen',true);
end

function value = local_sample(simOut,name,time)
value = sample_logged_signal(simOut.get(name),time,'linear');
value = double(value);
if size(value,2) == 1, value = value(:,1); end
end

function value = local_class(c)
if isfield(c,'stage2_expected_class'), value = char(c.stage2_expected_class); ...
elseif c.group == "nonideal" || c.group == "parameter_mismatch" || ...
        c.group == "angle_sampling", value = 'nonideal'; ...
else, value = 'ideal'; end
end

function value = local_rms(x)
if isempty(x), value=NaN; else, value=sqrt(mean(x.^2)); end
end

function value = local_mean(x)
if isempty(x), value=NaN; else, value=mean(x); end
end

function value = local_max_abs(x)
if isempty(x), value=NaN; else, value=max(abs(x)); end
end
