function [checks,aggregate] = evaluate_stage3_acceptance(p64,p128,diagnostics, ...
        pairs,drift,sensitivity,cfg,complete)
%EVALUATE_STAGE3_ACCEPTANCE Apply the locked Scheme-5 contract.

g = cfg.gates.stage3;
p64 = p64(:); p128 = p128(:); diagnostics = diagnostics(:);
pairs = pairs(:); drift = drift(:); sensitivity = sensitivity(:);
checks = struct();
checks.full_scope = logical(complete);
checks.m64_all_profiles = numel(p64) == 8;
checks.m128_all_profiles = numel(p128) == 8;
checks.m64_coverage = local_all_min(p64,'coverage_fraction',1);
checks.m128_coverage = local_all_min(p128,'coverage_fraction',1);
checks.m64_fusion_count = local_all_min(p64,'fusion_count',g.fusion_count_min);
checks.active_convergence = local_all(p64, ...
    'last_active_update_rms_e_rad',g.final_active_update_rms_max_e_rad) && ...
    local_all(p64,'previous_active_update_rms_e_rad', ...
    g.final_active_update_rms_max_e_rad);
checks.shadow_accuracy = local_all(p64,'shadow_rmse_e_rad', ...
    g.shadow_lut_rmse_max_e_rad);
checks.active_accuracy = local_all(p64,'active_rmse_e_rad', ...
    g.active_lut_rmse_max_e_rad) && local_all(p64, ...
    'active_max_error_e_rad',g.active_lut_max_error_e_rad);
fixed0 = local_by_id(p64,"fixed_00deg_e");
checks.fixed_zero_accuracy = ~isempty(fixed0) && ...
    fixed0.active_rmse_e_rad <= g.fixed_zero_lut_rmse_max_e_rad;
nonzero = p64(string({p64.case_id}) ~= "fixed_00deg_e");
checks.nonzero_lut_improvement = local_all_min(nonzero, ...
    'active_improvement_fraction',g.nonzero_lut_improvement_min);
checks.scheme4_agreement = local_all(p64,'scheme4_shadow_difference_e_rad', ...
    g.scheme4_lut_difference_max_e_rad) && local_all(p64, ...
    'scheme4_active_difference_e_rad',g.scheme4_lut_difference_max_e_rad);
checks.safety_constraints = local_logical_all(p64,'all_nodes_valid') && ...
    local_logical_all(p64,'finite_state') && ...
    local_logical_all(p64,'amplitude_constraint_satisfied') && ...
    local_logical_all(p64,'monotonic_constraint_satisfied');
checks.diagnostic_modes = numel(diagnostics) == 16 && ...
    local_all_min(diagnostics,'coverage_fraction',1) && ...
    local_logical_all(diagnostics,'finite_state') && ...
    local_logical_all(diagnostics,'amplitude_constraint_satisfied') && ...
    local_logical_all(diagnostics,'monotonic_constraint_satisfied');

primary64 = local_by_id(p64,cfg.stage3.primary_profile_id);
primary128 = local_by_id(p128,cfg.stage3.primary_profile_id);
checks.m128_not_worse = ~isempty(primary64) && ~isempty(primary128) && ...
    primary128.active_rmse_e_rad <= primary64.active_rmse_e_rad + ...
    g.m128_rmse_regression_max_e_rad;
checks.condition_drift = numel(drift) == 8 && local_all(drift, ...
    'lut_drift_e_rad',g.cross_condition_lut_drift_max_e_rad);
checks.sensitivity_complete = numel(sensitivity) == 10 && ...
    local_all_min(sensitivity,'valid_fraction',g.sensitivity_valid_fraction_min) && ...
    local_logical_all(sensitivity,'finite_diagnostics');

classes = string({pairs.expected_class});
ideal = pairs(classes == "ideal"); nonideal = pairs(classes == "nonideal");
saturation = pairs(classes == "saturation_diagnostic");
idealControl = ideal(string({ideal.case_id}) ~= "fixed_00deg_e");
checks.ideal_control_angle = local_pair_angles(idealControl,cfg);
checks.nonideal_control_angle = local_pair_angles(nonideal,cfg);
checks.ideal_physical_median = local_median_min(ideal, ...
    {'id_rms_improvement','prediction_residual_improvement', ...
    'torque_ripple_improvement'},g.ideal_median_physical_improvement_min);
checks.ideal_no_regression = local_physical_min(ideal, ...
    -g.ideal_per_case_regression_max);
checks.nonideal_physical_median = local_median_min(nonideal, ...
    {'id_rms_improvement','prediction_residual_improvement', ...
    'torque_ripple_improvement'},0);
checks.nonideal_no_regression = local_physical_min(nonideal, ...
    -g.nonideal_per_case_regression_max);
checks.iq_tracking = local_all(pairs(classes ~= "saturation_diagnostic"), ...
    'iq_tracking_change',g.iq_tracking_regression_max);
checks.mean_torque = local_all(pairs(classes ~= "saturation_diagnostic"), ...
    'mean_torque_change',g.mean_torque_change_max);
checks.saturation_diagnostic_present = isscalar(saturation) && ...
    isfinite(saturation.active.compensation_max_abs_e_rad) && ...
    saturation.active.compensation_max_abs_e_rad <= ...
    cfg.stage3.max_abs_lut_e_rad+100*eps;
values = struct2cell(checks);
checks.all_mandatory = all(cellfun(@(x)islogical(x) && isscalar(x) && x, ...
    values));

aggregate = struct('m64_profile_count',numel(p64), ...
    'm128_profile_count',numel(p128), ...
    'diagnostic_profile_count',numel(diagnostics), ...
    'frozen_pair_count',numel(pairs),'drift_count',numel(drift), ...
    'sensitivity_count',numel(sensitivity), ...
    'primary_m64_active_rmse_e_deg',local_deg(primary64,'active_rmse_e_rad'), ...
    'primary_m128_active_rmse_e_deg',local_deg(primary128,'active_rmse_e_rad'), ...
    'maximum_condition_drift_e_deg',rad2deg(max( ...
    local_values(drift,'lut_drift_e_rad'),[],'omitnan')));
end

function pass = local_pair_angles(values,cfg)
if isempty(values), pass=false; return; end
pass=true;
for k=1:numel(values)
    [item,~,~] = control_angle_gate(values(k), ...
        struct('case_id',values(k).case_id),cfg);
    pass=pass && item;
end
end
function pass = local_physical_min(values,limit)
pass = local_all_min(values,'id_rms_improvement',limit) && ...
    local_all_min(values,'prediction_residual_improvement',limit) && ...
    local_all_min(values,'torque_ripple_improvement',limit);
end
function pass = local_median_min(values,fields,limit)
if isempty(values), pass=false; return; end
pass=true;
for k=1:numel(fields)
    v=local_values(values,fields{k});
    pass=pass && all(isfinite(v)) && median(v)>=limit;
end
end
function pass = local_all(values,field,limit)
v=local_values(values,field); pass=~isempty(v) && all(isfinite(v)&v<=limit);
end
function pass = local_all_min(values,field,limit)
v=local_values(values,field); pass=~isempty(v) && all(isfinite(v)&v>=limit);
end
function pass = local_logical_all(values,field)
pass=~isempty(values) && all(arrayfun(@(x)isfield(x,field) && ...
    logical(x.(field)),values));
end
function values = local_values(input,field)
if isempty(input), values=zeros(0,1); return; end
values=arrayfun(@(x)local_field(x,field),input(:));
end
function value = local_field(input,field)
if isfield(input,field), value=double(input.(field)); else, value=NaN; end
end
function out = local_by_id(values,id)
if isempty(values), out=[]; return; end
i=find(string({values.case_id})==string(id),1);
if isempty(i), out=[]; else, out=values(i); end
end
function value = local_deg(input,field)
if isempty(input) || ~isfield(input,field), value=NaN; ...
else, value=rad2deg(input.(field)); end
end
