function [simOut,elapsed_s] = simulate_stage2_case(c,cfg,activeEnable, ...
        runtimeLut,simulationMode,modelName)
%SIMULATE_STAGE2_CASE Run one explicitly parameterized Stage-2 harness case.

if nargin < 5, simulationMode = 'rapid-accelerator'; end
if nargin < 6, modelName = 'angle_lut_stage2_harness'; end
isStage2 = strcmp(modelName,'angle_lut_stage2_harness');
isStage3 = strcmp(modelName,'angle_lut_stage3_harness');
isStage4 = strcmp(modelName,'angle_lut_stage4_harness');
if isStage2
    modelPath = cfg.project.stage2_harness_model;
elseif isStage3
    modelPath = cfg.project.stage3_harness_model;
elseif isStage4
    modelPath = cfg.project.stage4_harness_model;
else
    assert(strcmp(modelName,'angle_lut_harness'), ...
        'anglelut:Stage2UnexpectedModel', ...
        'Only the Stage-1 harness is allowed for the equivalence audit.');
    modelPath = cfg.project.harness_model;
end
assert(isfile(modelPath), ...
    'anglelut:MissingStage2Harness','Build the Stage-2 harness first.');
if ~bdIsLoaded(modelName), load_system(modelPath); end
assert(~(isStage2 || isStage3 || isStage4) || ...
    numel(runtimeLut) == cfg.stage2.runtime_nodes, ...
    'anglelut:Stage2RuntimeLutSize','Runtime LUT must have 512 nodes.');

simIn = Simulink.SimulationInput(modelName);
fixedBias = double(c.periodic_bias_m_rad);
if c.error_mode == cfg.encoder.ERROR_FIXED
    fixedBias = double(c.fixed_error_e_rad)/cfg.motor.pole_pairs;
end
initial = compute_frozen_equilibrium_initialization( ...
    c,cfg,fixedBias,activeEnable,runtimeLut);
vdcValue = cfg.motor.vdc_nominal_V;
if isfield(c,'vdc_override_V'), vdcValue = double(c.vdc_override_V); end
overrides = { ...
    'sensor_mode',uint8(c.sensor_mode); ...
    'encoder_error_mode',uint8(c.error_mode); ...
    'encoder_error_bias_m_rad',fixedBias; ...
    'encoder_error_amp1_m_rad',double(c.periodic_amp1_m_rad); ...
    'encoder_error_phase1_rad',double(c.periodic_phase1_rad); ...
    'encoder_error_amp2_m_rad',double(c.periodic_amp2_m_rad); ...
    'encoder_error_phase2_rad',double(c.periodic_phase2_rad); ...
    'theta0_e_rad',double(c.theta0_e_rad); ...
    'encoder_counts_per_rev',double(c.encoder_counts_per_rev); ...
    'angle_sample_period_s',1/cfg.timing.angle_sync_sample_Hz; ...
    'encoder_noise_std_m_rad',double(c.angle_noise_std_m_rad); ...
    'encoder_noise_seed',uint32(c.random_seed); ...
    'stage1_current_noise_std_A',double(c.current_noise_std_A); ...
    'stage1_current_noise_seed',uint32(c.random_seed); ...
    'pwm_deadtime_s',double(c.deadtime_s); ...
    'pwm_min_pulse_duty',double(c.min_pulse_duty); ...
    'inverter_voltage_drop_V',double(c.inverter_voltage_drop_V); ...
    'stage1_speed_target_rpm',double(c.omega_m_radps)/(2*pi); ...
    'stage1_speed_initial_revps',initial.omega_m_radps/(2*pi); ...
    'stage1_omega_m_initial_radps',initial.omega_m_radps; ...
    'stage1_speed_pi_initial_A',initial.speed_pi_output_A; ...
    'stage1_idq_initial_A',initial.plant_idq_A; ...
    'stage1_load_torque_Nm',double(c.load_torque_Nm); ...
    'stage1_ident_phase_s',cfg.timing.identification_event_offset_s; ...
    'T_ident',cfg.timing.T_ident_s; ...
    'stage1_overmod_epsilon',1e-12; ...
    'Vdc',vdcValue};
if isStage2
    overrides = [overrides; { ...
        'stage2_active_enable',logical(activeEnable); ...
        'stage2_runtime_lut_e_rad',double(runtimeLut(:)); ...
        'stage2_runtime_nodes',double(cfg.stage2.runtime_nodes)}];
end
if isStage3
    overrides = [overrides; { ...
        'stage3_active_enable',logical(activeEnable); ...
        'stage3_runtime_lut_e_rad',double(runtimeLut(:)); ...
        'stage3_runtime_nodes',double(cfg.stage3.runtime_nodes)}];
end
if isStage4
    overrides = [overrides; { ...
        'stage4_active_enable',logical(activeEnable); ...
        'stage4_runtime_lut_e_rad',double(runtimeLut(:)); ...
        'stage4_runtime_nodes',double(cfg.stage4.runtime_nodes)}];
end
for k = 1:size(overrides,1)
    simIn = simIn.setVariable(overrides{k,1},overrides{k,2}, ...
        'Workspace',modelName);
end
simIn = simIn.setModelParameter( ...
    'StopTime',sprintf('%.17g',double(c.stop_time_s)), ...
    'SimulationMode',char(simulationMode), ...
    'ReturnWorkspaceOutputs','on','SaveTime','off', ...
    'SaveOutput','off','SaveState','off');
tStart = tic;
simOut = sim(simIn);
elapsed_s = toc(tStart);
end
