function [state,metrics,history,reference,runtimeLut] = ...
        stream_scheme5_trace(trace,M,cfg,modeCode)
%STREAM_SCHEME5_TRACE One-pass deployment-only E30-E32 replay.

required = {'theta_m_raw_rad','theta_m_unwrapped_rad','y_A', ...
    'omega_e_est_radps','quality_weight','valid','evaluation_mask','time_s'};
assert(isstruct(trace) && all(isfield(trace,required)), ...
    'anglelut:Stage3TraceSchema','Stage-1 deployment trace is incomplete.');
assert(size(trace.y_A,2) == 2,'anglelut:Stage3YShape', ...
    'Stage-3 y_A must be an N-by-2 deployment residual.');
if nargin < 4, modeCode = cfg.stage3.primary_amplitude_mode_code; end
if M == 64
    state = anglelut.scheme5_init64(cfg,modeCode);
else
    state = anglelut.scheme5_init128(cfg,modeCode);
end
n = numel(trace.time_s);
history = local_history(n,M);
for k = 1:n
    sample = struct('phi_m_rad',double(trace.theta_m_raw_rad(k)), ...
        'y_d_A',double(trace.y_A(k,1)), ...
        'y_q_A',double(trace.y_A(k,2)), ...
        'omega_e_est_radps',double(trace.omega_e_est_radps(k)), ...
        'quality_weight',double(trace.quality_weight(k)), ...
        'theta_m_unwrapped_rad',double(trace.theta_m_unwrapped_rad(k)), ...
        'timestamp_s',double(trace.time_s(k)), ...
        'valid',logical(trace.valid(k) && trace.evaluation_mask(k)));
    if M == 64
        [state,event] = anglelut.scheme5_update64(state,sample,cfg);
    else
        [state,event] = anglelut.scheme5_update128(state,sample,cfg);
    end
    history.accepted(k) = event.accepted;
    history.tangent_residual(k) = event.tangent_residual;
    history.radial_residual(k) = event.radial_residual;
    history.normalized_step_e_rad(k) = event.normalized_step_e_rad;
    history.amplitude(k) = event.amplitude;
    if event.triggered
        history.fusion_count(end+1,1) = double(event.fusion_count);
        history.fusion_sample_index(end+1,1) = k;
        history.fusion_time_s(end+1,1) = double(trace.time_s(k));
        history.fusion_travel_m_rad(end+1,1) = ...
            state.total_abs_travel_m_rad;
        history.fusion_coverage_fraction(end+1,1) = ...
            event.coverage_fraction;
        history.active_update_rms_e_rad(end+1,1) = ...
            event.fusion.rms_step_e_rad;
        history.shadow_lut_e_rad(end+1,:) = ...
            event.shadow_lut_e_rad(:).';
        history.active_lut_e_rad(end+1,:) = ...
            event.active_lut_e_rad(:).';
    end
end

% Evaluation truth is intentionally read only after all learning updates.
assert(isfield(trace,'truth_error_e_rad'), ...
    'anglelut:Stage3TruthEvaluationMissing', ...
    'Truth is required only to score the completed Scheme-5 LUT.');
accepted = logical(trace.valid(:) & trace.evaluation_mask(:));
reference = anglelut.aggregate_reference_lut(trace.theta_m_raw_rad, ...
    trace.truth_error_e_rad,M,accepted);
shadowError = anglelut.wrap_to_pi(state.shadow_lut_e_rad-reference.lut_e_rad);
activeError = anglelut.wrap_to_pi(state.active_lut_e_rad-reference.lut_e_rad);
zeroError = anglelut.wrap_to_pi(-reference.lut_e_rad);
mask = reference.valid_mask & isfinite(shadowError) & isfinite(activeError);
activeDelta = circshift(state.active_lut_e_rad,-1)-state.active_lut_e_rad;
diagnostic = history.accepted & isfinite(history.tangent_residual) & ...
    isfinite(history.radial_residual);

metrics = struct('nodes',M,'amplitude_mode',local_mode_name(modeCode,cfg), ...
    'sample_count',n,'accepted_count',double(state.accepted_count), ...
    'effective_weight',state.total_effective_weight, ...
    'coverage_fraction',mean(double(state.valid_mask)), ...
    'reference_coverage_fraction',reference.coverage_fraction, ...
    'fusion_count',double(state.fusion_count), ...
    'total_abs_travel_m_rad',state.total_abs_travel_m_rad, ...
    'mechanical_revolutions',state.total_abs_travel_m_rad/(2*pi), ...
    'shadow_rmse_e_rad',local_rms(shadowError(mask)), ...
    'active_rmse_e_rad',local_rms(activeError(mask)), ...
    'baseline_rmse_e_rad',local_rms(zeroError(mask)), ...
    'active_max_error_e_rad',local_max_abs(activeError(mask)), ...
    'last_active_update_rms_e_rad',state.last_active_update_rms_e_rad, ...
    'previous_active_update_rms_e_rad', ...
    state.previous_active_update_rms_e_rad, ...
    'active_max_abs_e_rad',max(abs(state.active_lut_e_rad)), ...
    'minimum_monotonic_margin',min(1-activeDelta/( ...
    cfg.motor.pole_pairs*2*pi/M)), ...
    'all_nodes_valid',all(state.valid_mask), ...
    'finite_state',all(isfinite(state.shadow_lut_e_rad)) && ...
    all(isfinite(state.active_lut_e_rad)), ...
    'tangent_rms',local_rms(history.tangent_residual(diagnostic)), ...
    'radial_rms',local_rms(history.radial_residual(diagnostic)), ...
    'normalized_step_rms_e_rad', ...
    local_rms(history.normalized_step_e_rad(diagnostic)), ...
    'max_local_step_e_rad',state.max_local_step_e_rad);
metrics.shadow_rmse_e_deg = rad2deg(metrics.shadow_rmse_e_rad);
metrics.active_rmse_e_deg = rad2deg(metrics.active_rmse_e_rad);
metrics.baseline_rmse_e_deg = rad2deg(metrics.baseline_rmse_e_rad);
metrics.active_max_error_e_deg = rad2deg(metrics.active_max_error_e_rad);
metrics.active_improvement_fraction = 1-metrics.active_rmse_e_rad/max( ...
    metrics.baseline_rmse_e_rad,eps);
metrics.amplitude_constraint_satisfied = metrics.active_max_abs_e_rad <= ...
    cfg.stage3.max_abs_lut_e_rad+100*eps;
metrics.monotonic_constraint_satisfied = ...
    metrics.minimum_monotonic_margin >= cfg.stage3.monotonic_margin-100*eps;
runtimeLut = anglelut.resample_periodic_lut( ...
    state.active_lut_e_rad,cfg.stage3.runtime_nodes);
end

function h = local_history(n,M)
h.accepted = false(n,1);
h.tangent_residual = NaN(n,1);
h.radial_residual = NaN(n,1);
h.normalized_step_e_rad = zeros(n,1);
h.amplitude = NaN(n,1);
h.fusion_count = zeros(0,1);
h.fusion_sample_index = zeros(0,1);
h.fusion_time_s = zeros(0,1);
h.fusion_travel_m_rad = zeros(0,1);
h.fusion_coverage_fraction = zeros(0,1);
h.active_update_rms_e_rad = zeros(0,1);
h.shadow_lut_e_rad = zeros(0,M);
h.active_lut_e_rad = zeros(0,M);
end

function name = local_mode_name(code,cfg)
if code == cfg.stage3.MODE_NOMINAL
    name = 'nominal_model';
elseif code == cfg.stage3.MODE_MEASURED_MAGNITUDE
    name = 'measured_magnitude';
else
    name = 'direction_normalized';
end
end

function value = local_rms(x)
if isempty(x), value = NaN; else, value = sqrt(mean(x.^2)); end
end

function value = local_max_abs(x)
if isempty(x), value = NaN; else, value = max(abs(x)); end
end
