function [state,metrics,history,reference,runtimeLut] = ...
        stream_scheme2_trace(trace,M,cfg,mode)
%STREAM_SCHEME2_TRACE One-pass deployment-only E40 replay.
%   MODE is 'atan2' (default) or the separately whitelisted diagnostic
%   'atan2_free'.  Evaluation truth is read only after the update loop.

if nargin < 4, mode = "atan2"; end
mode = string(mode);
assert(isscalar(mode) && any(mode == ["atan2","atan2_free"]), ...
    'anglelut:Stage4Mode','Mode must be atan2 or atan2_free.');
common = {'theta_m_raw_rad','theta_m_unwrapped_rad','quality_weight', ...
    'valid','evaluation_mask','time_s'};
if mode == "atan2"
    required = [common,{'z_euler_rad'}];
    sourceMode = cfg.stage4.MODE_ATAN2;
else
    required = [common,{'y_A'}];
    sourceMode = cfg.stage4.MODE_ATAN2_FREE;
end
assert(isstruct(trace) && all(isfield(trace,required)), ...
    'anglelut:Stage4TraceSchema','Stage-1 deployment trace is incomplete.');
if mode == "atan2_free"
    assert(size(trace.y_A,2) == 2,'anglelut:Stage4YShape', ...
        'Stage-4 y_A must be an N-by-2 deployment residual.');
end
if M == 64
    state = anglelut.scheme2_init64(cfg,sourceMode);
elseif M == 128
    state = anglelut.scheme2_init128(cfg,sourceMode);
else
    error('anglelut:Scheme2NodeCount', ...
        'Scheme 2 supports fixed M=64 or M=128.');
end

n = numel(trace.time_s);
history = local_history(n,M);
for k = 1:n
    sampleValid = logical(trace.valid(k) && trace.evaluation_mask(k));
    if mode == "atan2"
        sample = struct('phi_m_rad',double(trace.theta_m_raw_rad(k)), ...
            'z_e_rad',double(trace.z_euler_rad(k)), ...
            'quality_weight',double(trace.quality_weight(k)), ...
            'theta_m_unwrapped_rad', ...
            double(trace.theta_m_unwrapped_rad(k)), ...
            'timestamp_s',double(trace.time_s(k)),'valid',sampleValid);
        if M == 64
            [state,event] = anglelut.scheme2_update64(state,sample,cfg);
        else
            [state,event] = anglelut.scheme2_update128(state,sample,cfg);
        end
    else
        sample = struct('phi_m_rad',double(trace.theta_m_raw_rad(k)), ...
            'y_d_A',double(trace.y_A(k,1)), ...
            'y_q_A',double(trace.y_A(k,2)), ...
            'quality_weight',double(trace.quality_weight(k)), ...
            'theta_m_unwrapped_rad', ...
            double(trace.theta_m_unwrapped_rad(k)), ...
            'timestamp_s',double(trace.time_s(k)),'valid',sampleValid);
        if M == 64
            [state,event] = anglelut.scheme2_update_atan2_free64( ...
                state,sample,cfg);
        else
            [state,event] = anglelut.scheme2_update_atan2_free128( ...
                state,sample,cfg);
        end
    end
    history.accepted(k) = event.accepted;
    history.updated(k) = event.updated;
    history.decimated(k) = event.decimated;
    history.innovation_e_rad(k) = event.innovation_e_rad;
    history.raw_sine_innovation(k) = event.raw_sine_innovation;
    history.sine_innovation(k) = event.sine_innovation;
    history.normalized_step_e_rad(k) = event.normalized_step_e_rad;
    if event.triggered
        history.fusion_count(end+1,1) = double(event.fusion_count);
        history.fusion_sample_index(end+1,1) = k;
        history.fusion_time_s(end+1,1) = double(trace.time_s(k));
        history.fusion_travel_m_rad(end+1,1) = ...
            state.total_abs_travel_m_rad;
        history.fusion_coverage_fraction(end+1,1) = ...
            event.coverage_fraction;
        history.active_update_rms_e_rad(end+1,1) = ...
            event.fusion.rms_step_e_rad;
        history.smoothing_applied(end+1,1) = event.smoothing_applied;
        history.shadow_lut_e_rad(end+1,:) = ...
            event.shadow_lut_e_rad(:).';
        history.active_lut_e_rad(end+1,:) = ...
            event.active_lut_e_rad(:).';
    end
end

% Evaluation-only truth is intentionally accessed after every update.
assert(isfield(trace,'truth_error_e_rad'), ...
    'anglelut:Stage4TruthEvaluationMissing', ...
    'Truth is required only to score the completed Scheme-2 LUT.');
accepted = logical(trace.valid(:) & trace.evaluation_mask(:));
reference = anglelut.aggregate_reference_lut(trace.theta_m_raw_rad, ...
    trace.truth_error_e_rad,M,accepted);
shadowError = anglelut.wrap_to_pi( ...
    state.shadow_lut_e_rad-reference.lut_e_rad);
activeError = anglelut.wrap_to_pi( ...
    state.active_lut_e_rad-reference.lut_e_rad);
zeroError = anglelut.wrap_to_pi(-reference.lut_e_rad);
mask = reference.valid_mask & isfinite(shadowError) & ...
    isfinite(activeError);
activeDelta = circshift(state.active_lut_e_rad,-1)- ...
    state.active_lut_e_rad;
hit = double(state.node_hits);
nodeVariance = NaN(M,1);
varianceMask = hit > 1;
nodeVariance(varianceMask) = ...
    state.node_step_M2_e_rad2(varianceMask)./(hit(varianceMask)-1);

metrics = struct('nodes',M,'mode',char(mode), ...
    'sample_count',n,'accepted_count',double(state.accepted_count), ...
    'update_count',double(state.update_count), ...
    'decimated_count',double(state.decimated_count), ...
    'update_decimation',cfg.stage4.update_decimation, ...
    'decimation_semantics', ...
    'every Nth eligible sample; invalid samples do not advance phase', ...
    'effective_weight',state.total_effective_weight, ...
    'coverage_fraction',mean(double(state.valid_mask)), ...
    'reference_coverage_fraction',reference.coverage_fraction, ...
    'fusion_count',double(state.fusion_count), ...
    'smoothing_event_count',double(state.smoothing_event_count), ...
    'total_abs_travel_m_rad',state.total_abs_travel_m_rad, ...
    'mechanical_revolutions',state.total_abs_travel_m_rad/(2*pi), ...
    'shadow_rmse_e_rad',local_rms(shadowError(mask)), ...
    'active_rmse_e_rad',local_rms(activeError(mask)), ...
    'baseline_rmse_e_rad',local_rms(zeroError(mask)), ...
    'active_max_error_e_rad',local_max_abs(activeError(mask)), ...
    'last_active_update_rms_e_rad', ...
    state.last_active_update_rms_e_rad, ...
    'previous_active_update_rms_e_rad', ...
    state.previous_active_update_rms_e_rad, ...
    'active_max_abs_e_rad',max(abs(state.active_lut_e_rad)), ...
    'minimum_monotonic_margin',min(1-activeDelta/( ...
    cfg.motor.pole_pairs*2*pi/M)), ...
    'all_nodes_valid',all(state.valid_mask), ...
    'finite_state',all(isfinite(state.shadow_lut_e_rad)) && ...
    all(isfinite(state.active_lut_e_rad)), ...
    'minimum_node_hits',min(hit), ...
    'maximum_node_hits',max(hit), ...
    'node_hit_coefficient_of_variation',local_cv(hit), ...
    'minimum_cumulative_gain',min(state.node_cumulative_gain), ...
    'maximum_cumulative_gain',max(state.node_cumulative_gain), ...
    'cumulative_gain_coefficient_of_variation', ...
    local_cv(state.node_cumulative_gain), ...
    'mean_node_step_variance_e_rad2', ...
    local_mean_finite(nodeVariance), ...
    'maximum_node_step_variance_e_rad2', ...
    local_max_finite(nodeVariance), ...
    'sine_innovation_rms',local_rms( ...
    history.sine_innovation(history.accepted)), ...
    'normalized_step_rms_e_rad',local_rms( ...
    history.normalized_step_e_rad(history.updated)), ...
    'max_local_step_e_rad',state.max_local_step_e_rad);
metrics.shadow_rmse_e_deg = rad2deg(metrics.shadow_rmse_e_rad);
metrics.active_rmse_e_deg = rad2deg(metrics.active_rmse_e_rad);
metrics.baseline_rmse_e_deg = rad2deg(metrics.baseline_rmse_e_rad);
metrics.active_max_error_e_deg = rad2deg(metrics.active_max_error_e_rad);
metrics.active_improvement_fraction = 1-metrics.active_rmse_e_rad/max( ...
    metrics.baseline_rmse_e_rad,eps);
metrics.amplitude_constraint_satisfied = metrics.active_max_abs_e_rad <= ...
    cfg.stage4.max_abs_lut_e_rad+100*eps;
metrics.monotonic_constraint_satisfied = ...
    metrics.minimum_monotonic_margin >= ...
    cfg.stage4.monotonic_margin-100*eps;
runtimeLut = anglelut.resample_periodic_lut( ...
    state.active_lut_e_rad,cfg.stage4.runtime_nodes);
end

function h = local_history(n,M)
h.accepted = false(n,1);
h.updated = false(n,1);
h.decimated = false(n,1);
h.innovation_e_rad = NaN(n,1);
h.raw_sine_innovation = NaN(n,1);
h.sine_innovation = NaN(n,1);
h.normalized_step_e_rad = zeros(n,1);
h.fusion_count = zeros(0,1);
h.fusion_sample_index = zeros(0,1);
h.fusion_time_s = zeros(0,1);
h.fusion_travel_m_rad = zeros(0,1);
h.fusion_coverage_fraction = zeros(0,1);
h.active_update_rms_e_rad = zeros(0,1);
h.smoothing_applied = false(0,1);
h.shadow_lut_e_rad = zeros(0,M);
h.active_lut_e_rad = zeros(0,M);
end

function value = local_rms(x)
if isempty(x), value = NaN; else, value = sqrt(mean(x.^2)); end
end

function value = local_max_abs(x)
if isempty(x), value = NaN; else, value = max(abs(x)); end
end

function value = local_cv(x)
x = double(x(:));
if isempty(x) || mean(x) == 0, value = NaN; ...
else, value = std(x,1)/mean(x); end
end

function value = local_mean_finite(x)
x = x(isfinite(x));
if isempty(x), value = NaN; else, value = mean(x); end
end

function value = local_max_finite(x)
x = x(isfinite(x));
if isempty(x), value = NaN; else, value = max(x); end
end
