function defs = bus_definitions(createObjects)
%BUS_DEFINITIONS Specifications and optional Simulink.Bus objects.
%   DEFS = BUS_DEFINITIONS(false) is side-effect free and can run without
%   loading a model. DEFS = BUS_DEFINITIONS(true) additionally creates bus
%   objects in DEFS.objects; it never assigns them to the base workspace.

if nargin < 1
    createObjects = false;
end

defs.schema_version = "stage1-buses-v1";
defs.IdentificationBus = [ ...
    spec("iabc_A", [3 1], "double", "A", "measured phase currents at interval boundary"); ...
    spec("duty_abc", [3 1], "double", "1", "duty effective during the interval"); ...
    spec("vdc_V", 1, "double", "V", "measured DC-link voltage"); ...
    spec("theta_m_raw_rad", 1, "double", "rad", "wrapped raw mechanical angle"); ...
    spec("theta_m_unwrapped_rad", 1, "double", "rad", "continuous raw mechanical angle"); ...
    spec("theta_e_rad", 1, "double", "rad", "raw electrical angle p*theta_m+theta0"); ...
    spec("omega_e_radps", 1, "double", "rad/s", "available estimated electrical speed"); ...
    spec("adc_valid", 1, "boolean", "1", "current sample validity"); ...
    spec("encoder_valid", 1, "boolean", "1", "angle sample/extrapolation validity"); ...
    spec("pwm_saturated", 1, "boolean", "1", "PWM overmodulation or saturation flag"); ...
    spec("pwm_overmodulated", 1, "boolean", "1", "PWM overmodulation flag"); ...
    spec("min_pulse_clipped", 1, "boolean", "1", "minimum-pulse clipping flag"); ...
    spec("current_limited", 1, "boolean", "1", "current controller limit flag"); ...
    spec("direction_sign", 1, "int8", "1", "hysteretic direction in {-1,0,+1}"); ...
    spec("direction_valid", 1, "boolean", "1", "direction is observable and stable"); ...
    spec("timestamp_s", 1, "double", "s", "identification event timestamp"); ...
    spec("current_timestamp_s", 1, "double", "s", "timestamp represented by iabc"); ...
    spec("voltage_timestamp_s", 1, "double", "s", "start of represented duty interval"); ...
    spec("angle_timestamp_s", 1, "double", "s", "timestamp represented by raw angle"); ...
    spec("angle_age_s", 1, "double", "s", "age of last physical encoder sample")];

defs.EvaluationTruthBus = [ ...
    spec("theta_m_true_rad", 1, "double", "rad", "true mechanical angle; evaluation only"); ...
    spec("theta_e_true_rad", 1, "double", "rad", "true electrical angle; evaluation only"); ...
    spec("omega_m_true_radps", 1, "double", "rad/s", "true mechanical speed; evaluation only"); ...
    spec("omega_e_true_radps", 1, "double", "rad/s", "true electrical speed; evaluation only"); ...
    spec("injected_error_m_rad", 1, "double", "rad", "injected mechanical error; evaluation only"); ...
    spec("injected_error_e_rad", 1, "double", "rad", "injected electrical error; evaluation only"); ...
    spec("plant_vabc_V", [3 1], "double", "V", "plant-applied phase voltage; evaluation only"); ...
    spec("plant_vdq_V", [2 1], "double", "V", "plant-applied dq voltage; evaluation only"); ...
    spec("timestamp_s", 1, "double", "s", "truth timestamp")];

defs.identification_name = "IdentificationBus";
defs.truth_name = "EvaluationTruthBus";
defs.truth_policy = ...
    "Truth bus may connect only to evaluation, metrics, and plotting paths.";
defs.source_bus_policy = ...
    "RawIdentificationSourceBus and RawEvaluationTruthSourceBus are model " + ...
    "observer feeds, not the formal interfaces. IdentificationBus must be " + ...
    "assembled completely before the residual loop; EvaluationTruthBus is " + ...
    "assembled only after that loop and remains evaluation-only.";

if createObjects
    defs.objects.IdentificationBus = makeBus(defs.IdentificationBus, ...
        "Deployment-safe Stage 1 measurements and timestamps");
    defs.objects.EvaluationTruthBus = makeBus(defs.EvaluationTruthBus, ...
        "Simulation truth for evaluation only");
else
    defs.objects = struct();
end
end

function s = spec(name, dimensions, dataType, unit, description)
s = struct('Name', char(name), 'Dimensions', dimensions, ...
    'DataType', char(dataType), 'Unit', char(unit), ...
    'Description', char(description));
end

function bus = makeBus(specs, description)
elements(1, numel(specs)) = Simulink.BusElement;
for k = 1:numel(specs)
    elements(k).Name = specs(k).Name;
    elements(k).Dimensions = specs(k).Dimensions;
    elements(k).DataType = specs(k).DataType;
    elements(k).Complexity = 'real';
    elements(k).Unit = specs(k).Unit;
    elements(k).Description = specs(k).Description;
end
bus = Simulink.Bus;
bus.Description = description;
bus.Elements = elements;
end
