function contract = stage0_artifact_contract()
%STAGE0_ARTIFACT_CONTRACT Required static and per-run Stage 0 artifacts.

projectRoot = fileparts(fileparts(mfilename('fullpath')));
contract.schema_version = "stage0-artifacts-v2";
contract.entrypoint = fullfile(projectRoot, 'run_stage0.m');
contract.latest_pointer = fullfile(projectRoot, 'results', 'latest_stage0.txt');
contract.required_project_files = string({ ...
    fullfile(projectRoot, 'docs', 'preflight_report.md'), ...
    fullfile(projectRoot, 'docs', 'formula_block_map.md'), ...
    fullfile(projectRoot, 'config', 'signal_map.m'), ...
    fullfile(projectRoot, 'config', 'timing_contract.m')}).';
contract.required_run_files = ["gate.json", "run_manifest.json", "result.json", ...
    "file_inventory.csv", "file_inventory.json"];
contract.allowed_status = ["PASS", "FAIL", "BLOCKED"];
contract.required_gate_checks = [ ...
    "required_files", "model_loaded", "solver_preserved", ...
    "parameters_match", "required_signals", "model_update", ...
    "model_clean_after_update", "baseline_simulation", ...
    "source_hash_unchanged", "file_inventory_written", ...
    "environment_manifest_recorded"];
contract.required_manifest_fields = [ ...
    "run_id", "stage", "created_at", "matlab_version", "model_path", ...
    "model_sha256_before", "model_sha256_after", "parameters", ...
    "environment", "file_inventory", "final_status", ...
    "baseline_elapsed_s"];
end
