function matrix = stage3_case_matrix(cfg)
%STAGE3_CASE_MATRIX Same streams and frozen cases as Scheme 4.

if nargin < 1, cfg = stage3_config(); end
base = stage2_case_matrix(cfg);
matrix = base;
matrix.schema_version = "stage3-case-matrix-v1";
matrix.amplitude_modes = [cfg.stage3.primary_amplitude_mode, ...
    cfg.stage3.diagnostic_amplitude_modes];
matrix.condition_drift_ids = ["speed_-20radps_m","speed_-10radps_m", ...
    "speed_-05radps_m","speed_+05radps_m","speed_+10radps_m", ...
    "speed_+20radps_m","load_0Nm","load_2Nm"];
matrix.sensitivity_ids = ["mismatch_Rs_-10percent", ...
    "mismatch_Rs_+10percent","mismatch_Ls_-10percent", ...
    "mismatch_Ls_+10percent","mismatch_psi_-10percent", ...
    "mismatch_psi_+10percent","nonideal_deadtime", ...
    "nonideal_voltage_drop","nonideal_delay_5us", ...
    "nonideal_delay_50us"];
end
